version: '3'

services:
  go-nginx:
    container_name: go-nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.docker/nginx/logs:/var/log/nginx
      - ./app/secret:/GO/src/sheeputech/app/secret
      - ./app/services:/GO/src/sheeputech/app/services
      - ./app/static:/GO/src/sheeputech/app/static
      - ./app/views:/GO/src/sheeputech/app/views
      - ./app/main.go:/GO/src/sheeputech/app/main.go
      - gomod:/GO/src/sheeputech/app/go.mod
      - gosum:/GO/src/sheeputech/app/go.sum
      - vendor:/GO/src/sheeputech/app/vendor
    ports:
      - '80:80'

volumes:
  gomod:
  gosum:
  vendor: