version: '3'

services:
  go-nginx:
    container_name: go-nginx
    restart: always
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    volumes:
      - ./.docker/nginx/logs:/var/log/nginx
      - ./backend-go/services:/GO/src/sheeputech/backend-go/services
      - ./backend-go/static:/GO/src/sheeputech/backend-go/static
      - ./backend-go/views:/GO/src/sheeputech/backend-go/views
      - ./backend-go/main.go:/GO/src/sheeputech/backend-go/main.go
      - ./backend-go/go.mod:/GO/src/sheeputech/backend-go/go.mod
      - ./backend-go/go.sum:/GO/src/sheeputech/backend-go/go.sum
      - ./backend-go/vendor:/GO/src/sheeputech/backend-go/vendor
    ports:
      - '80:80'