version: '3'

services:
  go-nginx:
    container_name: go-nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nginx-logs:/var/log/nginx
      - ./app/static:/GO/src/sheeputech/app/static
      - ./app/views:/GO/src/sheeputech/app/views
      - ./app/services:/GO/src/sheeputech/app/services
      - ./app/main.go:/GO/src/sheeputech/app/main.go
      - ./app/go.mod:/GO/src/sheeputech/app/go.mod
      - ./app/go.sum:/GO/src/sheeputech/app/go.sum
      - ./app/vendor:/GO/src/sheeputech/app/vendor
    ports:
      - '80:80'

volumes:
  nginx-logs: