version: '3'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    ports:
      - '8080:8080'

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: on-failure
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql: