version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    volumes:
      - ./frontend-vue/dist:/var/www/html
    ports:
      - '80:80'
#  backend:
#    container_name: backend
#    build:
#      context: .docker/go
#      dockerfile: Dockerfile