version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: frontend/.docker
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    volumes:
      - ./frontend/dist:/var/www/html
    ports:
      - '80:80'

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    ports:
      - '8080:8080'